### ISSUE TITLE
npm install twitter fails

### ISSUE THREAD

**Issue by cedricpinson** [jdub/node-twitter#10]
npm info it worked if it ends with ok
npm info using npm@0.2.3-3
npm info fetch http://registry.npmjs.org/twitter/-/twitter-0.1.16.tgz
npm info fetch http://registry.npmjs.org/cookie/-/cookie-0.1.5.tgz
npm info fetch http://registry.npmjs.org/oauth/-/oauth-0.9.0.tgz
npm info install twitter@v0.1.16
npm info install cookie@0.1.5
npm info install oauth@0.9.0
npm ERR! Failed unpacking the tarball.
npm ERR! This is very rare. Perhaps the 'gzip' or 'tar' configs
npm ERR! are set improperly?
npm ERR! 
npm ERR! install failed Error: Failed gzip "--decompress" "--stdout" "/usr/local/lib/node/.npm/.cache/twitter/v0.1.16/package.tgz"
npm ERR! install failed exited with 1
npm ERR! install failed     at ChildProcess.<anonymous> (/usr/local/lib/node/.npm/npm/0.2.3-3/package/lib/utils/exec.js:41:19)
npm ERR! install failed     at ChildProcess.emit (events.js:67:17)
npm ERR! install failed     at Socket.<anonymous> (child_process.js:172:12)
npm ERR! install failed     at Socket.emit (events.js:64:17)
npm ERR! install failed     at Array.2 (net.js:825:12)
npm ERR! install failed     at EventEmitter._tickCallback (node.js:126:26)
npm info install failed rollback
npm info not installed twitter,v0.1.16
npm info not installed cookie,0.1.5
npm info not installed oauth,0.9.0
npm info install failed rolled back
npm ERR! Error: Failed gzip "--decompress" "--stdout" "/usr/local/lib/node/.npm/.cache/twitter/v0.1.16/package.tgz"
npm ERR! exited with 1
npm ERR!     at ChildProcess.<anonymous> (/usr/local/lib/node/.npm/npm/0.2.3-3/package/lib/utils/exec.js:41:19)
npm ERR!     at ChildProcess.emit (events.js:67:17)
npm ERR!     at Socket.<anonymous> (child_process.js:172:12)
npm ERR!     at Socket.emit (events.js:64:17)
npm ERR!     at Array.2 (net.js:825:12)
npm ERR!     at EventEmitter._tickCallback (node.js:126:26)
npm ERR! npm install <tarball file>
npm ERR! npm install <tarball url>
npm ERR! npm install <folder>
npm ERR! npm install <pkg>
npm ERR! npm install <pkg>@<tag>
npm ERR! npm install <pkg>@<version>
npm ERR! npm install <pkg>@<version range>
npm ERR! 
npm ERR! Can specify one or more: npm install ./foo.tgz bar@stable /some/folder
npm ERR! Installs '.' if no argument supplied
npm ERR! try running: 'npm help install'
npm ERR! Report this _entire_ log at http://github.com/isaacs/npm/issues
npm ERR! or email it to npm-@googlegroups.com
npm not ok

**Comment by cedricpinson** [comment]
Maybe it's because of node version, I use 0.4.4

**Comment by cedricpinson** [comment]
forget it, It's because of my npm version
